{% set version = "0.2.0" %}

package:
  name: ipybertin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipybertin/ipybertin-{{ version }}.tar.gz
  sha256: 89252f6dbef635e94751863328d338d9af6fcb90699f11a08d4bf29a476a7964

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
    - yarn
    - jupyterlab =3
    - jupyter-packaging
  run:
    - python >=3.6
    - ipywidgets >=7.0.0

test:
  imports:
    - ipybertin
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipybertin/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipybertin/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipybertin/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipybertin\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipybertin\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipybertin\\package.json (exit 1)          # [win]

about:
  home: https://github.com/davidbrochart/ipybertin
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Jupyter - Bertin.js bridge
  doc_url: https://github.com/davidbrochart/ipybertin
  dev_url: https://github.com/davidbrochart/ipybertin

extra:
  recipe-maintainers:
    - davidbrochart
